unsigned int length_string(char *) ;
void str_split(unsigned int, char *, unsigned int *, char ***) ;
unsigned int str_to_ui(char *) ;
int str_to_i(char *) ;
double str_to_d(char *) ;
int str_cmp(char *, char *, unsigned int) ;
void str_cpy(char *, unsigned int, char *) ;
void memory_copy(void *src, void *dest, size_t n) ;
char *str_merge(char *, char *) ;
void print_bin(void *, unsigned int) ;
int checkDifferArray(unsigned int *, unsigned int) ;
void ui_cpy(unsigned int, unsigned int *, unsigned int *) ;